PUT localhost:8000/user/register
Content-Type: application/json

{
  "username": "admin",
  "password": "123",
  "email": "123@qq.com",
  "phone": "1234"
}

###
POST localhost:8000/user/login
Content-Type: application/json

{
  "username": "admin",
  "password": "123"
}