PUT localhost:8000/user/register
Content-Type:  application/json; charset=UTF-8

{
  "username": "张一",
  "password": "123",
  "email": "abc@xyz.com",
  "phone": "+8801712345678"
}


###
GET localhost:8000/user/findAll


###
DELETE localhost:8000/user
Content-Type: application/json; charset=UTF-8

{
"id": 3
}


###
PUT localhost:8000/user/update
Content-Type: application/json; charset=UTF-8


{
  "id": 33,
  "username": "admin",
  "email": "123@qq.com",
  "phone": "08123856789"
}

###模糊查询
GET localhost:8000/user/findSome?userName=1

