PUT localhost:8000/user/register
Content-Type:  application/json; charset=UTF-8

{
  "username": "张一z",
  "password": "123",
  "email": "abc@xyz.com",
  "phone": "+8801712345678"
}


###
PUT localhost:8000
Content-Type:  application/json; charset=UTF-8

{
  "userId": "1",
  "productId": "1",
  "quantity": "1",
  "price": "1"
}

###
GET localhost:8000/user/findAll


###
GET localhost:8000/petstore/findAll

###
DELETE localhost:8000/user
Content-Type: application/json; charset=UTF-8

{
"id": 42
}


###
PUT localhost:8000/user/update
Content-Type: application/json; charset=UTF-8


{
  "id": 107,
  "username": "李四",
  "email": "123@qq.com",
  "phone": "08123856789",
  "consignee":  "Jimmy",
  "address": "32 Baker Street"
}

###模糊查询
GET localhost:8000/user/findSome?username=1


###
PUT localhost:8000/petstore/add
Content-Type: application/json; charset=UTF-8

{
  "goodsType":  "1",
  "goodsname": "1",
  "goodsPrice": "1",
  "goodsDesc":  "1",
  "goodsStatus": "1"
}

###添加宠物知识信息
PUT localhost:8000/petKnowledge/insert
Content-Type: application/json; charset=UTF-8

{
  "title": "宠物健康",
  "author": "eee",
  "description": "ddfv",
  "content": "content",
  "essayType": "宠物知识"

}

###查询所有宠物知识信息
GET localhost:8000/petKnowledge/findAll
Content-Type: application/json; charset=UTF-8

###根据文章的种类查找宠物知识
GET localhost:8000/petKnowledge/selectByType
Content-Type: application/json; charset=UTF-8

{
  "essayType": "宠物养生"
}

###根据时间查找宠物知识
GET localhost:8000/petKnowledge/selectByTime
Content-Type: application/json; charset=UTF-8

###查找评论
GET localhost:8000/comment/findAll?issueId=44

###删除评论
DELETE localhost:8000/comment?id=13

###模糊查询评论
GET localhost:8000/comment/findSome?content=1&issueId=44

###删除宠物秀
DELETE localhost:8000/petIssue
Content-Type: application/json

{
  "id": 43
}


